/**
 * Shared journal context builder.
 *
 * Builds the context string injected at session start across all LLM agents
 * (pi, Claude Code, OpenCode). Contains:
 *   - Global instructions
 *   - TODO.md (if it exists)
 *   - 3 most recent journal entries (full content)
 *   - Filename listing of older entries (up to 30)
 *   - Cross-project awareness (5 recent filenames per other project)
 *   - Harvest cheat-sheet when the project's meta.json sets a harvest flag
 *
 * Used as:
 *   - Library: import { buildJournalContext } from "./index.ts"
 *   - CLI: bun extensions/shared/journal-context.ts [cwd] (also consumed via
 *     --part <name> by the Claude Code / OpenCode hooks)
 *
 * Config is read from ~/.config/llm/journal.json (generated by Nix).
 */

import { existsSync, readFileSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

/** Max recent filenames to list for the current project. */
const FILENAME_LIST_CURRENT = 30;
/** Max recent filenames to list per other project. */
const FILENAME_LIST_OTHER = 5;

/** Only files matching this pattern are treated as journal entries. */
const JOURNAL_FILE_RE = /^\d{4}-\d{2}-\d{2}-\d{2}-.+\.md$/;

function isJournalFile(filename: string): boolean {
  return JOURNAL_FILE_RE.test(filename);
}

export interface ProjectMeta {
  description?: string;
  path?: string;
  /** Flag: this project tracks time with the harvest CLI. true = standard policy; object = + private project notes. */
  harvest?: boolean | { note?: string };
}

export async function loadProjectMeta(projectDir: string): Promise<ProjectMeta | null> {
  const metaPath = join(projectDir, "meta.json");
  if (!existsSync(metaPath)) return null;
  try {
    return JSON.parse(await readFile(metaPath, "utf-8")) as ProjectMeta;
  } catch {
    return null;
  }
}

export interface JournalConfig {
  notesDir: string;
  noNotesReminder: string;
  journalReminder: string;
  compactionReminder: string;
  journalSkipMessage: string;
  vanillaMessage: string;
  globalInstructions: string;
}

export interface NotesResult {
  exists: boolean;
  path: string;
  notes: Array<{ filename: string; content: string }>;
  /** All .md filenames (excluding TODO.md), most recent first. */
  allFilenames: string[];
  /** Contents of TODO.md if it exists. */
  todo: string | null;
}

/**
 * Time-tracking policy injected when a project's meta.json carries a harvest
 * flag. The text lives in harvest-policy.md (sibling file, edited as prose) and
 * is generic by design: it ships from shared code to every agent, so it names
 * no account, client, domain, or note-taking policy — company/entry policies
 * live in the meta.json harvest note (private journal tree), appended verbatim
 * below the policy.
 */
export function loadHarvestPolicy(): string {
  const path = fileURLToPath(new URL("./harvest-policy.md", import.meta.url));
  const text = readFileSync(path, "utf-8");
  if (text.trim() === "") throw new Error(`empty harvest policy file: ${path}`);
  return text.replace(/\n+$/, "");
}

/** Pure given the policy text: the injection block for a meta.json harvest flag. */
export function buildHarvestBlock(policy: string, harvest: NonNullable<ProjectMeta["harvest"]>): string {
  const note = typeof harvest === "object" && harvest.note?.trim() ? `\nProject notes: ${harvest.note.trim()}` : "";
  return `${policy}${note}`;
}

export function loadJournalConfig(): JournalConfig {
  const configDir = process.env.XDG_CONFIG_HOME || join(process.env.HOME || "", ".config");
  const path = join(configDir, "llm", "journal.json");
  return JSON.parse(readFileSync(path, "utf-8")) as JournalConfig;
}

export async function getRecentNotes(notesDir: string, projectName: string): Promise<NotesResult> {
  const projectNotes = join(notesDir, projectName);

  if (!existsSync(projectNotes)) {
    return { exists: false, path: projectNotes, notes: [], allFilenames: [], todo: null };
  }

  const files = await readdir(projectNotes);
  const journalFiles = files.filter(isJournalFile).sort().reverse();

  const todoPath = join(projectNotes, "TODO.md");
  const todo = existsSync(todoPath) ? await readFile(todoPath, "utf-8") : null;

  if (journalFiles.length === 0) {
    return { exists: true, path: projectNotes, notes: [], allFilenames: [], todo };
  }

  const recentFiles = journalFiles.slice(0, 3);
  const notes = await Promise.all(
    recentFiles.map(async (filename) => {
      const content = await readFile(join(projectNotes, filename), "utf-8");
      return { filename, content };
    }),
  );

  return { exists: true, path: projectNotes, notes, allFilenames: journalFiles, todo };
}

async function getOtherProjectFilenames(notesDir: string, projectName: string): Promise<string[]> {
  const projectNotes = join(notesDir, projectName);
  if (!existsSync(projectNotes)) return [];

  const files = await readdir(projectNotes);
  return files.filter(isJournalFile).sort().reverse().slice(0, FILENAME_LIST_OTHER);
}

async function getOtherProjectSummaries(notesDir: string, currentProject: string): Promise<string | null> {
  if (!existsSync(notesDir)) return null;

  const dirs = await readdir(notesDir, { withFileTypes: true });
  const projects: Array<{
    name: string;
    description: string | null;
    path: string | null;
    filenames: string[];
    mostRecent: string;
  }> = [];

  for (const dir of dirs) {
    if (!dir.isDirectory() || dir.name === currentProject) continue;
    const filenames = await getOtherProjectFilenames(notesDir, dir.name);
    if (filenames.length === 0) continue;
    const meta = await loadProjectMeta(join(notesDir, dir.name));
    projects.push({
      name: dir.name,
      description: meta?.description ?? null,
      path: meta?.path ?? null,
      filenames,
      mostRecent: filenames[0],
    });
  }

  if (projects.length === 0) return null;

  // Sort by most recent entry (filenames are date-prefixed, descending)
  projects.sort((a, b) => b.mostRecent.localeCompare(a.mostRecent));

  const lines = projects.map((p) => {
    const names = p.filenames.join(", ");
    const desc = p.description ? ` — ${p.description}` : "";
    const path = p.path ? ` [${p.path}]` : "";
    return `  ${p.name}${desc}${path}: ${names}`;
  });
  return `Other project journals (recent entries):\n${lines.join("\n")}`;
}

/**
 * Structured journal context split into parts, each under the 10K char hook
 * output limit for Claude Code. Pi uses buildJournalContext() which joins them.
 */
export interface JournalParts {
  /** Global instructions + journal behavioral guidance */
  instructions: string;
  /** TODO.md + directory listing + cross-project awareness */
  metadata: string;
  /** Individual journal entries (most recent first), one per element */
  journals: string[];
}

export async function buildJournalParts(config: JournalConfig, cwd: string): Promise<JournalParts> {
  const empty: JournalParts = { instructions: "", metadata: "", journals: [] };

  if (process.env.LLM_VANILLA === "1") {
    return { ...empty, instructions: config.vanillaMessage };
  }

  let instructions = config.globalInstructions;

  if (process.env.NO_JOURNAL === "1") {
    return { ...empty, instructions: `${instructions}\n\n${config.journalSkipMessage}` };
  }

  instructions += `\n\n${config.journalReminder}`;

  const projectName = basename(cwd);
  const projectDir = join(config.notesDir, projectName);
  const meta = await loadProjectMeta(projectDir);
  const result = await getRecentNotes(config.notesDir, projectName);
  const harvestBlock =
    meta?.harvest === true || (meta?.harvest !== undefined && typeof meta.harvest === "object")
      ? buildHarvestBlock(loadHarvestPolicy(), meta.harvest)
      : null;

  const metaParts: string[] = [];
  const journals: string[] = [];

  if (result.notes.length === 0) {
    let noNotes = `No previous session notes for ${projectName}.\nNotes directory: ${result.path}/\n`;
    if (!result.exists) {
      noNotes += "(Directory does not exist yet — it will be created when the first journal entry is written)\n";
    }
    const metaPath = join(projectDir, "meta.json");
    if (!existsSync(metaPath)) {
      noNotes += `\nNo meta.json found. Create ${metaPath} with {"description": "...", "path": "~/..."} to help other sessions understand this project.`;
    }
    noNotes += `\n${config.noNotesReminder}`;
    metaParts.push(noNotes);
    if (harvestBlock) metaParts.push(harvestBlock);
  } else {
    const desc = meta?.description ? ` — ${meta.description}` : "";
    const path = meta?.path ? ` [${meta.path}]` : "";
    metaParts.push(`Previous session notes for ${projectName}${desc}${path}:`);
    const metaPath = join(projectDir, "meta.json");
    if (!existsSync(metaPath)) {
      metaParts.push(
        `No meta.json found. Create ${metaPath} with {"description": "...", "path": "~/..."} to help other sessions understand this project.`,
      );
    } else if (!meta?.description || !meta?.path) {
      metaParts.push(`meta.json is missing fields. Update ${metaPath} to include both "description" and "path".`);
    } else {
      metaParts.push(`If the description or path in meta.json seems wrong, update ${metaPath}.`);
    }

    if (harvestBlock) metaParts.push(harvestBlock);

    if (result.todo) {
      metaParts.push(`<file name="${result.path}/TODO.md">\n${result.todo}\n</file>`);
    }

    for (const note of result.notes) {
      journals.push(`<file name="${result.path}/${note.filename}">\n${note.content}\n</file>`);
    }

    if (result.allFilenames.length > 3) {
      const olderFilenames = result.allFilenames.slice(3, FILENAME_LIST_CURRENT);
      const total = result.allFilenames.length;
      let listing = olderFilenames.join("\n");
      if (total > FILENAME_LIST_CURRENT) {
        listing += `\n... and ${total - FILENAME_LIST_CURRENT} more`;
      }
      metaParts.push(
        `<directory-listing name="${result.path}" description="Older entries (${total} total, use read tool if relevant)">\n${listing}\n</directory-listing>`,
      );
    }
  }

  const otherProjects = await getOtherProjectSummaries(config.notesDir, projectName);
  if (otherProjects) {
    metaParts.push(otherProjects);
  }

  return { instructions, metadata: metaParts.join("\n\n"), journals };
}

/** Full context string (used by Pi, backward compatible). */
export async function buildJournalContext(config: JournalConfig, cwd: string): Promise<string> {
  const parts = await buildJournalParts(config, cwd);
  return [parts.instructions, parts.metadata, ...parts.journals].filter(Boolean).join("\n\n");
}

/** Resolve a named part from JournalParts. Returns empty string for missing journal indices. */
export function resolvePart(parts: JournalParts, name: string): string {
  if (name === "instructions") return parts.instructions;
  if (name === "metadata") return parts.metadata;
  if (name.startsWith("journal:")) {
    const idx = parseInt(name.split(":")[1], 10);
    return parts.journals[idx] ?? "";
  }
  return "";
}

/** CLI entry point. Exported for testing. */
export async function main(args: string[]): Promise<string> {
  const { values, positionals } = parseArgs({
    args,
    options: { part: { type: "string" } },
    allowPositionals: true,
  });
  const cwd = positionals[0] || process.cwd();
  const config = loadJournalConfig();

  if (values.part) {
    const parts = await buildJournalParts(config, cwd);
    return resolvePart(parts, values.part);
  }
  return buildJournalContext(config, cwd);
}

// CLI mode:
//   bun .../journal-context.ts [cwd]                  -- full context (Pi, legacy)
//   bun .../journal-context.ts --part <name> [cwd]    -- single part (Claude Code hooks)
//     Parts: instructions, metadata, journal:0, journal:1, journal:2
const isMainModule = typeof process !== "undefined" && process.argv[1]?.includes("journal-context");

if (isMainModule) {
  main(process.argv.slice(2)).then((output) => process.stdout.write(output));
}
